### ISSUE TITLE
get wget working on Apple Silicon

### ISSUE THREAD

**Issue by zdavatz** [claui/homebrew-public#2]
@claui can you please try to get wget working on Apple Silicon? Currently I am getting the following:

```
brew install wget
Updating Homebrew...
Error: dlopen(/Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.bundle - /Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:7:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/formula.rb:21:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:4:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:4:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `require?'
/usr/local/Homebrew/Library/Homebrew/commands.rb:35:in `valid_internal_cmd?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:85:in `<main>'
Error: dlopen(/Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.bundle - /Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:7:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/formula.rb:21:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:5:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `require?'
/usr/local/Homebrew/Library/Homebrew/commands.rb:35:in `valid_internal_cmd?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:85:in `<main>'
```

**Comment by claui** [comment]
@zdavatz Looking into it!

**Comment by zdavatz** [comment]
thank you!

**Comment by claui** [comment]
@zdavatz I assume you haven’t re-installed Homebrew during the last few days?

On November 12, Homebrew [2.5.10](https://github.com/Homebrew/brew/releases/tag/2.5.10) came out. It has a [breaking change](https://github.com/Homebrew/brew/pull/9117), which affects pretty much every user of ARM-native Homebrew.

@domschl’s https://github.com/Homebrew/brew/issues/7857#issuecomment-726668719 explains how you can keep brewing on the DTK:

> ### How to keep brewing
> 
> Latest brew versions for Apple silicon do not support `/usr/local` as path for ARM brews anymore. In order to fix this, uninstall that existing homebrew and start anew at `/opt/homebrew`, following the remarks for ARM in the guide for [manual homebrew installation](https://docs.brew.sh/Installation).
> 
> Once brew is installed, make sure that `/opt/homebrew/bin` is in your path, and use `brew doctor` to create all necessary directories and owernships.
> 
> Once `brew doctor` is happy, do `brew update` and start installing. […]

(I’ve removed the part about code signing, which is now obsolete and can be ignored.)

The necessary steps in a bit more detail:
- Uninstall Homebrew from `/usr/local` no matter what.
- Decide whether you want to use Homebrew under Rosetta, natively on ARM or both. We publicly recommend the Rosetta method. But as you’re already familiar with the state of ARM-native Homebrew, you can ignore that warning and make an informed decision yourself.
- If you want to use Homebrew under Rosetta, re-install freshly at `/usr/local` by running the shell one-liner at https://brew.sh/.
- If you want to use Homebrew natively on ARM, re-install freshly at `/opt/homebrew` by `cd`-ing to `/opt` and running the shell-one-liner in the [Alternative Installs » Untar anywhere](https://docs.brew.sh/Installation#untar-anywhere) section. We’ve made that step deliberately hard. This is to keep users who are unaware of the still-experimental state of native ARM support from shooting themselves in the foot.
- If you want both, follow both steps.

Let me know if that works for you.

**Comment by zdavatz** [comment]
ok, I am trying the `ARM` way first:
```
zdavatz@Zenos-tKit /opt/homebrew/bin (master) $ ./brew install wget
Error: dlopen(/Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.bundle - /Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1/lib/fiddle.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Library/Homebrew/linkage_checker.rb:7:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Library/Homebrew/formula.rb:21:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Library/Homebrew/formula_installer.rb:5:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Library/Homebrew/cmd/install.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Library/Homebrew/utils.rb:88:in `require?'
/opt/homebrew/Library/Homebrew/commands.rb:35:in `valid_internal_cmd?'
/opt/homebrew/Library/Homebrew/brew.rb:85:in `<main>'
```

**Comment by zdavatz** [comment]
If I try the Rosetta 2 way I get:
```
cd /usr/local
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
Homebrew is only supported on Intel processors!
```
did I forget to remove a directory?

I removed these three directories:
```
sudo rm -r Caskroom
sudo rm -r Cellar
sudo rm -r Frameworks
```

**Comment by claui** [comment]
Regarding the ARM issue (dlopen error): looks you still have a very early workaround active for FB7823402, which Apple has solved in the meantime.

To fix this, try:

```
sudo gem uninstall fiddle --version=1.0.1; sudo rm -rf /Library/Ruby/Gems/2.6.0/gems/fiddle-1.0.1
```

and you should be good to go.

Regarding that issue installing the Intel flavour, I’d recommend that you run the [uninstall script](https://github.com/homebrew/install#uninstall-homebrew) to clean up all traces of the existing ARM flavour from `/usr/local`:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
```

**Comment by zdavatz** [comment]
The Rosetta way still does not seem to work for me:
![latest-screenshot](https://user-images.githubusercontent.com/4953/99229503-667b7a00-27ee-11eb-859a-6f9ee767252a.png)

**Comment by zdavatz** [comment]
The ARM ways seems to work now!

**Comment by claui** [comment]
Regarding the Intel issue: this should absolutely not happen at all.
At the very least, you should have gotten a more verbose error message that explains how you’re supposed to run the installer under Rosetta. 🤔
We may be on to a bug in the Homebrew installer here.

Investigating.

**Comment by zdavatz** [comment]
thank you @claui - the ARM way is working great!

**Comment by claui** [comment]
@zdavatz Ok, turns out our installer’s error messages don’t have the same verbosity as `brew install` yet. Error message parity is still a work in progress.

Regarding the Intel installer, can you try prepending `arch -x86_64` and see if it makes a difference?

```
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

**Comment by zdavatz** [comment]
yes, great, this works, thank you!
